import { Form } from './FormSubmit';
import type { NextPage } from 'next';
import Head from 'next/head';
interface EmailProps {
  id: string;
  __component: string;
  title: string;
  description: string;
  emailPlaceholder: string;
  submitButton: {
    text: string;
  };
}

// const Home: NextPage = () => {
//   return (
//     <div>
//       <Head>
//         <title>Contact form with Sendgrid</title>
//         <meta name='description' content='Generated by create next app' />
//         <link rel='icon' href='/favicon.ico' />
//       </Head>
//       <main className='h-screen'>
//         <h1 className='text-6xl text-center my-10'>
//           Contact form with <span className='text-blue-500'>SendGrid</span>
//         </h1>
//         <div className='container mx-auto my-10 max-w-7xl cpx-4 sm:px-6 lg:px-60'>
//           <Form />
//         </div>
//       </main>
//     </div>
//   );
// };
// export default Home;

export default function Email({ data }: { data: EmailProps }) {
  return (
    <section className='py-6 dark:bg-black dark:text-gray-50'>
      <div className='container max-w-5xl mx-auto flex-col justify-center p-4 space-y-8 md:p-10 lg:space-y-0 lg:space-x-12 lg:justify-between lg:flex-row'>
        <div className='flex flex-col space-y-4 text-center lg:text-left'>
          <h1 className='text-5xl font-bold leading-none'>{data.title}</h1>
          <p className='text-lg'>{data.description}</p>
        </div>
        {/* <Form
          placeholder={data.emailPlaceholder}
          text={data.submitButton.text}
        /> */}
        <Form {...Form} />{' '}
      </div>{' '}
    </section>
  );
}
